#!/bin/bash
# usage: jpp <file.java>
# Script to preprocess and compile Java files containing LazyList macros
# A "processed" directory will be created, containing the .class file


PROC_DIR=processed
TMPFILE=$(mktemp /tmp/jpp.XXXX)

if [ $# -ne 1 ]; then
   echo "Usage: jpp <file.java>"
   exit 
fi

if [ ! -d $PROC_DIR ]; then
   echo "Creating $PROC_DIR ..."
   mkdir $PROC_DIR
fi

if [ -d $PROC_DIR/$1 ]; then
   rm -f $PROC_DIR/$1
fi


cat <<EOF > $TMPFILE
#define freeze(x)  ( ()->(x) )
#define LLmake(a, b) new LazyList<>((a), freeze(b))
#define Thunk(T)  Supplier<T>
EOF

cat $TMPFILE $1 | cpp -P - -o $PROC_DIR/$1
javac -classpath $PROC_DIR -d $PROC_DIR $PROC_DIR/$1
rm -f $TMPFILE


